# -*- coding: utf-8 -*-
"""Akhil_PreProcessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kDB2FPgtr3U-AsLXYB8dt9AmHztdSxZq
"""

import pandas as pd
import numpy as np

data={
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [12, 160, 2900, 2200, 2500, 3200],
    "Cost (Million $)": [200, 400, 650, 150, 250,1000],
    "CO2":[10,1000,20,100000,50,70]

}
energy_df=pd.DataFrame(data)
print(energy_df)

forward_filled_df=energy_df.fillna(method="ffill")
print(forward_filled_df)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
forward_filled_df[["Energy Consumption (MWh)","Cost (Million $)"]]=scaler.fit_transform(forward_filled_df[["Energy Consumption (MWh)","Cost (Million $)"]])
print("\nData After Standardization(Z Score Scaling):")
print(forward_filled_df)

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
forward_filled_df[['CO2']]=scaler.fit_transform(forward_filled_df[['CO2']])
print("\nData After Normalizing( Min-Max Scaling):")
print(forward_filled_df)

from sklearn.preprocessing import LabelEncoder
lebel_encoder=LabelEncoder()
lebel_coded_df=forward_filled_df
lebel_coded_df['Energy Source']=lebel_encoder.fit_transform(lebel_coded_df['Energy Source'])
lebel_coded_df

forward_filled_df=pd.get_dummies(energy_df,columns=["Energy Source"])
print("\nData After One-Hot Encoding Categorical Variables:")
print(forward_filled_df)

forward_filled_df=pd.get_dummies(energy_df,columns=["Energy Source"])
print("\nData After One Hot Encoding Categorical Variables:")
print(forward_filled_df)