# -*- coding: utf-8 -*-
"""Akhil_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rnQA81AIVUK0fIcef6tW5jVL1kFqphQj
"""

import pandas as pd
import numpy as np

data={
    "Energy Source":["Solar","Wind","Hydropower","Geothermal","Biomass","Nuclear"],
    "Energy Consumption(MWh)":[1200,np.nan,2900,np.nan,2500,3200],
    "Cost(Million $)":[200,400,np.nan,150,250,np.nan]
}
energy_df=pd.DataFrame(data)
print("Origional Energy Data With Missing Values:")
print(energy_df)

cleaned_df=energy_df.dropna(subset="Energy Consumption(MWh)")


print(energy_df)
print("\nDataframe After removing none values")
print(cleaned_df)

#impute null values in Energy Consumption(MWh)
energy_df.iloc[:,1]=energy_df["Energy Consumption(MWh)"].fillna(energy_df["Energy Consumption(MWh)"].mean())

#impute null values in Cost(Million $)
energy_df.iloc[:,2]=energy_df["Cost(Million $)"].fillna(energy_df["Cost(Million $)"].mean())

print("\nDataframe after imputing missing values:")
print(energy_df)

forward_filled_df=energy_df.fillna(method="ffill")

print(energy_df)
print("\nData After Forward Filling:")
print(forward_filled_df)

energy_df["Cost per MWh"]=forward_filled_df["Energy Consumption(MWh)"]*1000000/forward_filled_df["Cost(Million $)"]

print("Cost per MWh:")
print(energy_df)