# -*- coding: utf-8 -*-
"""Akhil_numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDaL2mDrazN-ivCT8r8WSo-atEk4bdJY
"""

import numpy as np


d_4 = np.array([[ #3d
    [
        [1,2,3],
        [3,4,5],
        [6,7,8]],
    [
        [7,8,9],
        [10,11,12],
        [13,14,15]],
               [
                   [21,22,23],
                   [24,25,26],
                   [27,28,29]]
               ],
               [ #3d
    [
        [1,2,3],
        [3,4,5],
        [6,7,8]],
    [
        [7,8,9],
        [10,11,12],
        [13,14,15]],
               [
                   [21,22,23],
                   [24,25,26],
                   [27,28,29]]
               ]])
print(np.ndim(d_4), "\n", d_4)

d_0 = np.array(42) #0d
d_1 = np.array([1,2,3,4]) #1d
d_2 = np.array([  #2d
    [1,2,3],
    ('t', 'u', 'p',),
    ('t', 'u', 'p',),
    ('t', 'u', 'p',),
    ('t', 'u', 'p',)
])
d_3 = np.array([ #3d
    [
        [1,2,3],
        [3,4,5],
        [6,7,8]],
    [
        [7,8,9],
        [10,11,12],
        [13,14,15]],
               [
                   [21,22,23],
                   [24,25,26],
                   [27,28,29]]
               ])
print(np.ndim(d_0), "\n", d_0)
print(np.ndim(d_1), "\n", d_1)
print(np.ndim(d_2), "\n", d_2)
print(np.ndim(d_3), "\n", d_3)
print(f" d_3[0,2,2] {d_3[0,2,2]}  + d_3[1,1,2]  { d_3[1,1,2]}  = {d_3[1,1,2] + d_3[0,2,2] } ")

d_03 = d_3.reshape(-1,9)
print("reshaped", d_03)
d_013 = d_2.flatten()
print(d_013)

give list which starts with 0 till 50 with 3 step as list_1

list_1=[]
for i in range(0,100,1):
    list_1.append(i)

arr=np.array(list_1)
print("1",arr,type(arr))
print("2",arr[0:33:2])
print("3",arr[::2])
print("4",arr[::])

from typing import Generator

def alphabet_generator() -> Generator[str, None, None]:
    """Generates letters of the alphabet from 'a' to 'z'."""
    for char_code in range(ord('a'), ord('z') + 1):
        yield chr(char_code)

# Example of how to use the generator:
alphabet_list = list(alphabet_generator())
ar=np.array(alphabet_list)
print(alphabet_list)
print("1",ar,type(arr))
print("2",ar[0:33:2])
print("3",ar[::2])
print("4",ar[::])

